openapi: 3.0.0
info:
  title: My Test API
  description: A brief description of your API.
  version: 1.0.0
  termsOfService: 'https://example.com/terms/'
  contact:
    name: API Support
    url: 'https://example.com/support'
    email: support@example.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://api.example.com/v1'
    description: Production server
paths: {}
components: {}
tags: []
