name: Vale Linter

on:
  pull_request:
    paths:
      - '**/*.md'      # Run Vale on markdown files only (or other specific files you want)
      - '**/*.yaml'    # Run Vale on YAML files if needed
  push:
    branches:
      - main           # Or your default branch

jobs:
  vale-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python for Vale
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Add Vale to PATH
        run: |
          echo "##vso[task.setvariable variable=PATH]$env:ProgramFiles\Vale\vale.exe;$env:PATH"

      - name: Run Vale Linter
        run: |
          # Ensure the styles are available to Vale
          export VALE_PATH=$(pwd)/styles
          vale --min-alert-level=warning --output=github --max-suggestions=10
